### ISSUE TITLE
Attribute type longtext should implement method unserializeData() and  serializeData()

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/attribute_longtext#14]
## Checklist before I submit this issue report

I confirm that:
- [x] I have tested this with the latest version available
- [x] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [ ] I have checked the Contao community forums for references https://community.contao.org/
- [x] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/attribute_longtext/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        |          |               5.x - 7.0.x                   |
| Contao version:                     |          |                 3.5x.x                 |
| MetaModels version:                 |          |                Current                  |
| Installation via composer           | (yes/no) |                  Yes                |
| Installed MetaModels packages       |          |                all                  |

## Issue description

```php
PHP Deprecated notice: Attribute type longtext should implement method unserializeData() and  serializeData(). in composer/vendor/metamodels/core/src/MetaModels/MetaModel.php on line 461
#0 [internal function]: __error(16384, 'Attribute type ...', '/var/www/kunden...', 461, Array)
#1 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(461): trigger_error('Attribute type ...', 16384)
#2 composer/vendor/metamodels/core/src/MetaModels/MetaModel.php(690): MetaModels\MetaModel->getItemsWithId(Array, Array)
#3 system/modules/dms/src/DMS/Contao/Cron/MailListSend.php(101): MetaModels\MetaModel->findByFilter(Object(MetaModels\Filter\Filter))
#4 system/modules/dms/src/DMS/Contao/Cron/MailListSend.php(73): DMS\Contao\Cron\MailListSend->loadData()
#5 mail.php(42): DMS\Contao\Cron\MailListSend->sendMail()
#6 {main}
```

## Steps to reproduce

Create a longtext attribute in a MetaModels and open the Edit-Mask.

## Describe the behaviour of the application

Writes a warning into the log.

## Describe the expected behaviour of the application

No Error :)

**Comment by zonky2** [comment]
I check this at MM core b15... I don´t see the error or warning...

**Comment by stefanheimes** [comment]
Jokay, i have to check it again with my own testsystem. Maybe the version wasn't the right.

**Comment by richardhj** [comment]
Does @zonky2 needs to enable logging of PHP notices (debug level)?

**Comment by discordier** [comment]
> Does @zonky2 needs to enable logging of PHP notices (debug level)?

Yes :smile:
The methods are not implemented but can be implemented by copy&paste from base attribute.

**Comment by zonky2** [comment]
hmm... I count only 3 of 10 attributes that require this two methodes @discordier you are shure to implement both methodes at all?

**Comment by discordier** [comment]
The check in [MetaModel.php](https://github.com/MetaModels/core/blob/8a2f88d96a1263d20611b803215714931d2a7b02/src/MetaModels/MetaModel.php#L460) should be enough.

This attribute therefore really does not need to implement these methods, as there is no serialized data.

We might want to change the whole handling of serializing for 3.0 though.

**Comment by zonky2** [comment]
Have you a "notice issue" for serializing in 3.0
